### ISSUE TITLE
弱弱的来咨询一下后台这两个设置是什么意思

### ISSUE THREAD

**Issue by hcllmsx** [daocatt/flarum-ext-money-plus#2]
![image](https://github.com/user-attachments/assets/0c64b2f2-a273-4f02-9b1c-96b7408e21df)
【0 时不展示】这个好理解，就是用的金钱为0时，就在主页不展示这一项。
但是【当帖子被删除】和【当帖子被隐藏或被恢复时 (default)】这是啥意思啊，当帖子被删除时，是扣掉之前的奖励吗？当帖子被隐藏或被恢复时，相应的，隐藏就扣掉，恢复又增加金币，是我这样理解的吗？
感觉这两句，没写完整，......

**Comment by daocatt** [comment]
隐藏时会扣除，恢复时会增加
删除时会扣除

但是存在一个特殊情况，先隐藏再删除，插件没有做区分。可能会被扣两次。

#TODO 这个可以优化，但是最近没空更新。着急的话可以自己区分或者开启一个即可。
