### ISSUE TITLE
金币操作时间不对，群里有人说没有处理ISO 8601

### ISSUE THREAD

**Issue by hcllmsx** [daocatt/flarum-ext-money-plus#3]
群里还有人说这个插件也没有新建 Carbon ，但是直接 Date() 了

https://github.com/daocatt/flarum-ext-money-plus/blob/84819f357b210b5eee0cf796a0c5a441151b3107/src/History/Listeners/HistoryListeners.php#L26

https://github.com/daocatt/flarum-ext-money-plus/blob/84819f357b210b5eee0cf796a0c5a441151b3107/src/History/Listeners/MoneyAllHistoryListeners.php#L28

---

![image](https://github.com/user-attachments/assets/025e0a7a-1952-4488-a378-ba97ff38450d)
而我的docker容器已经设置了上海时区，依然无效。
![bee93e3c0715938659b94e830ffe4001](https://github.com/user-attachments/assets/90bce18d-d75c-40fe-9a9d-ea607932b41a)

希望大佬能修复一下这个问题

**Comment by daocatt** [comment]
config.php add

date_default_timezone_set('PRC');
