### ISSUE TITLE
大佬，再问一下，用这个钱包插件的时候，把那个回帖奖励改成-1

### ISSUE THREAD

**Issue by hcllmsx** [daocatt/flarum-ext-money-plus#5]
用这个钱包插件的时候，把那个回帖奖励改成-1。然后又当用户金钱为0的时候，我测试，好像会报错。但是依然会回帖成功。
在这种情况下，能不能弄成，如果金钱，扣除金钱不成功的时候，回帖也无法成功啊。.....

**Comment by daocatt** [comment]
了解，我确认下修改下

**Comment by daocatt** [comment]
Please check with v1.1.3
