### ISSUE TITLE
佬，如何给新注册的用户，默认赠送一定数量的货币呀

### ISSUE THREAD

**Issue by hcllmsx** [daocatt/flarum-ext-money-plus#6]
新用户刚注册，数量是0。我想让他们一注册，系统就赠送一定数量的货币。

**Comment by daocatt** [comment]
可以注册赠送

**Comment by hcllmsx** [comment]
在哪里设置这个呢...

**Comment by daocatt** [comment]
可能修改修改代码，你现在有使用什么注册相关的插件么

**Comment by hcllmsx** [comment]
与注册相关的，应该就只有
![image](https://github.com/user-attachments/assets/170bfbba-2511-41aa-a160-c31e1a93279a)
Email Filter过滤注册时电子邮件的，以及Turnstile注册时开了人机验证这个。好像没有别的了

**Comment by daocatt** [comment]
已更新增加注册设置

**Comment by hcllmsx** [comment]
> 已更新增加注册设置

emmmm，但是我更新之后，为啥....
![image](https://github.com/user-attachments/assets/bc9347e9-ae44-421e-9ea3-60976ce93fa1)
看上去还是只有之前那些设置，没有注册相关设置呀....

然后还有这个[https://github.com/daocatt/flarum-ext-money-plus/issues/2#issuecomment-2264553167](https://github.com/daocatt/flarum-ext-money-plus/issues/2#issuecomment-2264553167)描述信息，嘿嘿

**Comment by daocatt** [comment]
php flarum cache:clear

**Comment by hcllmsx** [comment]
> php flarum cache:clear

嗷，好吧，我直接用composer update这样更新了，确实应该要清理一遍缓存.....谢谢
